apiVersion: v1
kind: Service
metadata:
  name: {{ include "travelwithme-frontend.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
  selector:
    app: {{ include "travelwithme-frontend.fullname" . }}
