replicaCount: 1

frontend:
  image: react-frontend:latest
  replicaCount: 1
  servicePort: 80
  pullPolicy: IfNotPresent


resources: {}
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
