apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-with-db.fullname" . }}-mysql
  labels:
    {{- include "backend-with-db.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "backend-with-db.fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "backend-with-db.fullname" . }}-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ include "backend-with-db.fullname" . }}-mysql-pvc
