apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travelwithme-backend.fullname" . }}-backend
  labels:
    {{- include "travelwithme-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "travelwithme-backend.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "travelwithme-backend.fullname" . }}-backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']

      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
