apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend-with-db.fullname" . }}-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
