apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-with-db.fullname" . }}-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
  selector:
    app: {{ include "backend-with-db.fullname" . }}-frontend
