apiVersion: v1
kind: Service
metadata:
  labels:
    app: travelwithme-backend
  name: {{ include "backend-with-db.fullname" . }}-backend
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "backend-with-db.fullname" . }}-backend
