version: "3.9"

services:
  jenkins:
    network_mode: "host"
    build: .
    container_name: jenkins
    ports:
      - "9091:8080"   # UI Jenkins pe localhost:9090
      - "50000:50000"

    volumes:
      - ~/my_projects/jenkins_data:/var/jenkins_home
      - ./kubeconfig-minikube.yaml:/var/jenkins_home/.kube/config
      - ~/.aws:/var/jenkins_home/.aws:ro
      - /usr/bin/docker:/usr/bin/docker 
      - /var/run/docker.sock:/var/run/docker.sock 
      - ~/.minikube:/var/jenkins_home/.minikube:ro

volumes:
  jenkins_home:
