version: "3.9"

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "9091:8080"   # UI Jenkins pe localhost:9090
      - "50000:50000"

    volumes:
      - ~/my_projects/jenkins_data:/var/jenkins_home
      - ~/.kube:/root/.kube:ro   # acces la config-ul kubectl/helm

volumes:
  jenkins_home:
