replicas: 1

# Heap mic ca să nu omoare podul pe Minikube
esJavaOpts: "-Xms2048m -Xmx2048m"

resources:
  requests:
    cpu: "1"
    memory: "3072Mi"
  limits:
    memory: "3072Mi"

# PVC mic pentru demo
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi

# ⬇️ asta e esențial: elimină cluster.initial_master_nodes
masterService: ""
minimumMasterNodes: null

# Readiness probe relaxată - acceptă și cluster yellow
readinessProbe:
  exec:
    command:
      - bash
      - -c
      - |
        curl -s -k -u elastic:${ELASTIC_PASSWORD} https://127.0.0.1:9200/_cluster/health \
        | grep -E '"status":"(yellow|green)"'
  initialDelaySeconds: 30
  periodSeconds: 10
