apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "travelwithme-mysql.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
